<a href="https://colab.research.google.com/github/inunezfe/cs501hw/blob/main/CS501_HW4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import scipy.linalg as sc
import matplotlib.pyplot as plt

plt.style.use('seaborn-poster')
%matplotlib inline

# **Homework #4**

## Ivan Arturo Nuñez Ferro


### 1.

$(i)$ Consider the following polynomial:

\begin{equation}
p(x) = x^4 − 52x^3 + 854x^2 − 4628x^3 + 3825x^4
\end{equation}

Setup the companion matrix and compute the roots to the polynomial by computing the eigenvalues of the companion matrix. You may use MatLab for this. What are the function values at the roots that you computed?

In [6]:
from numpy.lib.polynomial import poly1d

# coefficients of the poly in descending order
c1 = [1,-52,854,-4628,3825]

# use the old polynomial for the companion matrix
p1 = poly1d(c1)

# use the new polynomial for the printing part
p_1 = np.polynomial.polynomial.Polynomial(p1.coef[::-1])

# calculate companion matrix
c = sc.companion(p1)

# calculate eigenvalues of the companion matrix
w,v = np.linalg.eig(c)

# evaluate polynomial with eigenvalues

zeros = np.polyval(p1,w)



print('The companion matrix is: ')
print(c)
print('The eigen values for said matrix are: ')
print(w)
print('Evaluating the polynomial')
print(zeros)



The companion matrix is: 
[[ 5.200e+01 -8.540e+02  4.628e+03 -3.825e+03]
 [ 1.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  1.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  1.000e+00  0.000e+00]]
The eigen values for said matrix are: 
[25. 17.  9.  1.]
Evaluating the polynomial
[-2.61024979e-10 -1.28238753e-10 -1.04591891e-11  0.00000000e+00]


As we can see, the values calculated after evaluating the polynomial using the eigenvalues calculated, all the results are zero or very close to zero. 

$(ii)$ For the following matrix, compute the characteristic polynomial and compute the eigenvalues and eigenvectors from the roots of the polynomial. You may not use MatLab for this.

\begin{equation}
\begin{bmatrix}
-2 & -4 & 2 \\
-2 & 1 & 2 \\
4 & 2 & 5
\end{bmatrix}
\end{equation}

### 2.

Consider the following matrix:

\begin{equation}
\begin{bmatrix}
2 & 1 & 2 \\
1 & 3 & 1 \\
2 & 1 & 6
\end{bmatrix}
\end{equation}

$(i)$ Compute the largest eigenvalue (in magnitude) and corresponding eigenvector through 10 iterations of the power method. You can use MatLab to compute matrix-vector products in a loop.

In [7]:
# define matrix and # of iterations
A = np.array([[2,1,2],[1,3,1],[2,1,6]])
iter = 10

# create random vector 
x = np.random.randint(10,size=3).reshape(3,1)

# we use the normalization power iteration
for i in range(iter):
  y = A.dot(x)
  x = y/np.linalg.norm(y, ord=np.inf)


# return the values after iteration
L_val = np.linalg.norm(y, ord=np.inf)
L_vec = x

print(f'The largest eigenvalue in magnitude is {L_val}')
print(f'The corresponding eigenvector through {iter} iterations is :\n{L_vec}')

The largest eigenvalue in magnitude is 7.236137679414106
The corresponding eigenvector through 10 iterations is :
[[0.44721892]
 [0.34165676]
 [1.        ]]


$(ii)$ Compute the smallest eigenvalue (in magnitude) and corresponding eigenvector through 10 iterations of the inverse power iteration method. You can use MatLab to compute inverse and matrix-vector products in a loop.



In [8]:
# calculate the inverse of A
B = np.linalg.inv(A)

# create random vector 
xb = np.random.randint(10,size=3).reshape(3,1)

# we use the inverse power iteration
for i in range(iter):
  yb = B.dot(x)
  xb = yb/np.linalg.norm(yb, ord=np.inf)


# return the values after iteration
L_val_b = np.linalg.norm(yb, ord=np.inf)
L_vec_b = xb

print(f'The smallest eigenvalue in magnitude is {L_val_b}')
print(f'The corresponding eigenvector through {iter} iterations is :\n{L_vec_b}')

The smallest eigenvalue in magnitude is 0.13819526994972375
The corresponding eigenvector through 10 iterations is :
[[0.44722754]
 [0.3416826 ]
 [1.        ]]


$(iii)$ Compute the eigenvalue closest to 2, through 10 iterations of the shifted inverse power iteration method. You can use MatLab to compute inverse and matrix-vector products in a loop.

In [9]:
# define sigma
sigma = 2

#define sigma i
s_i = sigma * np.eye(len(A))

# create A shifted and inverted
A_shift = np.linalg.inv(A - s_i)

# create random vector 
xs = np.random.randint(10,size=3).reshape(3,1)

# we use the shifted inverse power iteration
for i in range(iter):
  ys = A_shift.dot(xs)
  xs = ys/np.linalg.norm(ys, ord=np.inf)

# return the values after iteration
L_val_s = 1/(np.linalg.norm(ys, ord=np.inf)) + sigma
L_vec_s = xs

print(f'The smallest eigenvalue in magnitude is {L_val_s}')
print(f'The corresponding eigenvector through {iter} iterations is :\n{L_vec_s}')



The smallest eigenvalue in magnitude is 2.7792446546326515
The corresponding eigenvector through 10 iterations is :
[[ 0.21868381]
 [ 1.        ]
 [-0.43943915]]


### 3.

$(i)$ Consider the following matrix:


\begin{equation}
\begin{bmatrix}
2 & 1 & 1 \\
1 & 3 & 1 \\
1 & 1 & 4
\end{bmatrix}
\end{equation}

let $ v = [0.4, 0.5, 0.75]$ be the initial eigenvector estimate. Compute the corresponding eigen- value using Rayleigh Quotient. You may not use MatLab for this.

$(ii)$ For the matrix,

\begin{equation}
\begin{bmatrix}
1 & 2 & 0 \\
-2 & 1 & 2 \\
1 & 3 & 1
\end{bmatrix}
\end{equation}

Compute the dominant eigenvalue and eigenvector using 10 iterations of the Rayleigh Quotient Iterations. You may use MatLab for this.

In [10]:
# Defining matrix
A = np.array([[1,2,0],[-2,1,2],[1,3,1]])

# number of iterations
iter = 10

# create random vector 
xk = np.random.randint(1,10,size=3).reshape(3,1)


# Defining the raleigh iteration, that is a shifted power iteration


for i in range(iter):
  # calculate sigma
  aux = np.dot(xk.transpose(),A)
  sigma = np.dot(aux,xk)/np.dot(xk.transpose(),xk)
  s_i = sigma * np.eye(len(A))
  
  # create A shifted and inverted 
  # iteration stops when the matrix is singular, because sigma is a eigenvalue 
  try:
    A_shift = np.linalg.inv(A - s_i)

  except(np.linalg.LinAlgError):
    break

  # shifted power iteration
  yk = A_shift.dot(xk)
  xk = yk/np.linalg.norm(yk, ord=np.inf)


# return the values after iteration
L_val_s = sigma.item()
L_vec_s = xk

print(f'The dominant eigenvalue in magnitude is {L_val_s}')
print(f'The corresponding eigenvector through {iter} iterations is :\n{L_vec_s}')



The dominant eigenvalue in magnitude is 3.0
The corresponding eigenvector through 10 iterations is :
[[-0.5]
 [-0.5]
 [-1. ]]


### 4.

$(ii)$ Consider the matrix A:

\begin{equation}
A = 
\begin{bmatrix}
7 & 4 & 1 \\
4 & 4 & 4 \\
1 & 4 & 7
\end{bmatrix}
\end{equation}

The largest eigenvalue of A is 12. Compute the deflated matrix corresponding to A. You may not use MatLab for this.



$(ii)$ For the following matrix, run a simultaneous iteration with three vectors.

\begin{equation}
B =
\begin{bmatrix}
4 & -1 & 1 \\
-1 & 3 & -2 \\
1 & -2 & 3
\end{bmatrix}
\end{equation}

In [11]:
# matrix B
B = np.array([[4,-1,1],[-1,3,-2],[1,-2,3]])

# create random array of 3 by 3 
x = np.random.randint(1,10,size=(3,3))

print(f'random matrix before iteration: \n {x}')

# number of iteration
iter = 20

for i in range(iter):
  x = np.dot(B,x)

print(f'matrix after iteration: \n {x}')

for i in range(len(x)):
  # normalize
  eig_vec = x[:, i]/np.linalg.norm(x[:, i], ord=np.inf)

  # use raleigh quotient
  aux = np.dot(eig_vec.transpose(),B)
  eig_val = np.dot(aux,eig_vec)/np.dot(eig_vec.transpose(),eig_vec)

  print(f"Eigenvalue associated to x{i}: {eig_val}")
  print(f"Eigenvector associated to {eig_val}:\n {eig_vec}\n")



random matrix before iteration: 
 [[6 7 8]
 [3 6 8]
 [7 7 3]]
matrix after iteration: 
 [[ 12187204098301656   9749770949567007   3656182847553783]
 [-12187190151164047  -9749748285468394  -3656146236317567]
 [ 12187190151164057   9749748285468407   3656146236317578]]
Eigenvalue associated to x0: 5.999999999999127
Eigenvector associated to 5.999999999999127:
 [ 1.         -0.99999886  0.99999886]

Eigenvalue associated to x1: 5.9999999999963975
Eigenvector associated to 5.9999999999963975:
 [ 1.         -0.99999768  0.99999768]

Eigenvalue associated to x2: 5.999999999933153
Eigenvector associated to 5.999999999933153:
 [ 1.         -0.99998999  0.99998999]



$(iii)$ For the matrix B, run 10 orthogonal iterations to compute 2 Eigen-pairs simultaneously. You may use MatLab for this.

In [12]:
# create random array of 3 by 2 
x = np.random.randint(1,10,size=(3,2))

print(f'random array before iteration: \n {x}')

for i in range(10):
    
    # get the qr factorization of x
    Q, R = np.linalg.qr(x)
    
    # run a simultation iteration with the q part
    x = np.dot(B,Q)

print(f'array after iteration: \n {x}')

for i in range(0,2):
  # normalize
  eig_vec = x[:, i]/np.linalg.norm(x[:, i], ord=np.inf)

  # use raleigh quotient
  aux = np.dot(eig_vec.transpose(),B)
  eig_val = np.dot(aux,eig_vec)/np.dot(eig_vec.transpose(),eig_vec)

  print(f"Eigenvalue associated to x{i}: {eig_val}")
  print(f"Eigenvector associated to {eig_val}:\n {eig_vec}\n")



random array before iteration: 
 [[8 8]
 [5 3]
 [8 2]]
array after iteration: 
 [[-3.46809498 -2.44383248]
 [ 3.46209791 -1.2303739 ]
 [-3.46209811  1.23042057]]
Eigenvalue associated to x0: 5.999998002014227
Eigenvector associated to 5.999998002014227:
 [-1.          0.99827079 -0.99827085]

Eigenvalue associated to x1: 3.0000319672107945
Eigenvector associated to 3.0000319672107945:
 [-1.         -0.50346082  0.50347992]



### 5.

$(i)$ For the following matrix, run 10 Arnoldi iterations and compute the resulting matrix (you may use MatLab for this question)

\begin{equation}
A =
\begin{bmatrix}
1 & 3 & 2 \\
2 & 3 & 2 \\
2 & 1 & 2
\end{bmatrix}
\end{equation}

In [13]:
def arnoldi_iteration(A, b, n: int):
    """Computes a basis of the (n + 1)-Krylov subspace of A: the space
    spanned by {b, Ab, ..., A^n b}.

    Arguments
      A: m × m array
      b: initial vector (length m)
      n: dimension of Krylov subspace, must be >= 1
    
    Returns
      Q: m x (n + 1) array, the columns are an orthonormal basis of the
        Krylov subspace.
      h: (n + 1) x n array, A on basis Q. It is upper Hessenberg.  
    """
    eps = 1e-12
    h = np.zeros((n+1,n))
    Q = np.zeros((A.shape[0],n+1))
     # Normalize the input vector
    Q[:,0] =b/np.linalg.norm(b,2)   # Use it as the first Krylov vector
    for k in range(1,n+1):
        v = np.dot(A,Q[:,k-1])  # Generate a new candidate vector
        for j in range(k):  # Subtract the projections on previous vectors
            h[j,k-1] = np.dot(Q[:,j].T, v)
            v = v - h[j,k-1] * Q[:,j]
        h[k,k-1] = np.linalg.norm(v,2)
        if h[k,k-1] > eps:  # Add the produced vector to the list, unless
            Q[:,k] = v/h[k,k-1]
        else:  # If that happens, stop iterating.
            return Q, h
    return Q, h

In [14]:
# initial matrix
A = np.array([[1,3,2],[2,3,2],[2,1,2]])

# create random array of 3 by 2 
x = np.random.randint(1,10,size=(3,1)).ravel()

# run arnoldi iteration function

Q , h = arnoldi_iteration(A,x,20)

print(f"Non-zero columns of Q (basis of Krylov space): \n\n{Q[:,0:3]}\n")
print(f"A in terms of basis Q. (Hessemberg form) H: \n\n{h[0:3,0:3]}\n")

Non-zero columns of Q (basis of Krylov space): 

[[ 0.7448453  -0.20769813  0.63408751]
 [ 0.08276059  0.97173771  0.22108032]
 [ 0.66208471  0.11219318 -0.74098349]]

A in terms of basis Q. (Hessemberg form) H: 

[[ 3.89726027  2.92617756 -0.09550495]
 [ 2.81928159  2.12585293  0.47591332]
 [ 0.          1.88284333 -0.0231132 ]]



$(ii)$ Run orthogonal iterations on the resulting matrix and compute the eigenvalues.

In [15]:
H = h[0:3,0:3]

print(f"Hessemberg matrix: \n\n{H}\n")

for i in range(20):
    
    # get the qr factorization of x
    Q, R = np.linalg.qr(H)
    
    # run a simultation iteration with the q part
    H = np.dot(R,Q)

print("Eigenvalues of H:")
for i in range(0, 3):
    
    print(f"{H[i, i]:.3f}")

Hessemberg matrix: 

[[ 3.89726027  2.92617756 -0.09550495]
 [ 2.81928159  2.12585293  0.47591332]
 [ 0.          1.88284333 -0.0231132 ]]

Eigenvalues of H:
6.056
-0.989
0.933
